apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cedricclyburn-poi-map-app-dev
  annotations:
    argocd/app-name: cedricclyburn-poi-map-app-dev
    backstage.io/kubernetes-id: cedricclyburn-poi-map-app-dev
    backstage.io/kubernetes-namespace: cedricclyburn
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=cedricclyburn-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23JanusN/cedricclyburn-frontend
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/dev-pipelines/ns/cedricclyburn/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23bis.17gd.p1.openshiftapps.com/k8s/ns/cedricclyburn/deployments/poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23bis.17gd.p1.openshiftapps.com/#https://github.com/Summit23JanusN/cedricclyburn-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://poi-map-app-cedricclyburn.apps.summit23bis.17gd.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:ryanj"
  system: workshop-system-cedricclyburn
  consumesApis:
    - gateway-api-cedricclyburn
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-cedricclyburn
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:ryanj"
